[versions]
koin = "3.5.3"
kotest = "5.7.2"

[libraries]
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

kotest-framework-api = { module = "io.kotest:kotest-framework-api", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

mockk = { module = "io.mockk:mockk", version = "1.13.7" }
